Compile time fix 2
Apologies in advance if I mess up your code in progress! I will log
everything that I do so that the changes are easily reverted.

Assets/main_scene/scripts/UIManager.cs(31,47): error CS0103: The name
`pauseState' does not exist in the current context
- Fixed by changing the pauseState variable in OpenBag to bagState to
match the parameter

Assets/main_scene/scripts/UIManager.cs(31,24): error CS0122:
`UnityStandardAssets.Characters.FirstPerson.FirstPersonController.m_MouseLook'
is inaccessible due to its protection level
- Fixed by changing the variable m_Mouselook to public access

Assets/main_scene/scripts/UIManager.cs(43,36): error CS1061: Type
`UnityStandardAssets.Characters.FirstPerson.MouseLook' does not contain
a definition for `enabled' and no extension method `enabled' of type
`UnityStandardAssets.Characters.FirstPerson.MouseLook' could be found
(are you missing a using directive or an assembly reference?)
- Not fixed: Commented out lines 31 and 43 of UIManager because I didn't
know what to do with MouseLook.enabled