Added Jamie's code and my past changes to the current version
Vertex checking is sensitive to object scale but not rotation. Yet.

Runtime error fixed:
NullReferenceException: Object reference not set to an instance of an
object
UIManager.OpenBag (Boolean bagState) (at
Assets/main_scene/scripts/UIManager.cs:32)
UIManager.Update () (at
Assets/main_scene/scripts/UIManager.cs:26)

- Fixed by assigning the FPSController to the player variable in the
UIManager script